name: CI-CD Pipeline

on: [push, pull_request]

jobs:
  UnitTests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Unity Unit Tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    needs: UnitTests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - WebGL # WebGL.
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: false
      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - if: matrix.targetPlatform == 'Android'
        uses: jlumbroso/free-disk-space@v1.3.1
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

  # New job: Deploy to Itch.io
  DeployItchIo:
    name: Deploy to Itch.io 🚀
    needs: buildForAllSupportedPlatforms
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download WebGL Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: Build-WebGL
          path: build

      - name: Display Build Folder Structure
        run: ls -R
        working-directory: build/WebGL

      - name: Deploy 🚀 via GitHub Pages Deploy Action
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: itch-io
          folder: build/WebGL

      - name: Publish to Itch.io 🚀 via Butler
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: HTML
          ITCH_GAME: flyfire-designer
          ITCH_USER: vshirokun
          BRANCH: itch-io
          PACKAGE: build/WebGL
